fth TRIV is
    sort Elt .
endfth

fmod BTREE{X :: TRIV} is  
    protecting NAT .

    sorts NeBTree{X} BTree{X} .
    subsort NeBTree{X} < BTree{X} .

    op new : -> BTree{X} [ctor] .
    op _[_]_ : BTree{X} X$Elt BTree{X} -> NeBTree{X} [ctor] .
    op empty : BTree{X} -> Bool .
    op contains : BTree{X} X$Elt -> Bool .
    op root : NeBTree{X} -> X$Elt .
    op depth : BTree{X} -> Nat .
    op width : BTree{X} -> Nat .

    ops left right : NeBTree{X} -> BTree{X} .

    var E1 E2 : X$Elt .
    var R1 : NeBTree{X} .
    vars T1 T2 : BTree{X} .

    cmb R1 : NeBTree{X}
        if empty(R1) = false .

    eq empty(new) = true .
    eq empty(T1 [E1] T2) = false [owise] .

    eq left(new) = new .
    eq left(T1 [E1] T2) = T1 .

    eq right(new) = new .
    eq right(T1 [E1] T2) = T2 .

    eq contains(new, E1) = false .
    eq contains(T1, E1) = root(T1) == E1 or contains(left(T1),E1) or contains(right(T1),E1).

    eq root(T1 [E1] T2) = E1 .

    eq depth(new) = 0 .
    eq depth(T1 [E1] T2) = 1 + max(depth(T1), depth(T2)) .

    eq width(new) = 0 .
    eq width(T1 [E1] T2) = 1 + width(T1) + width(T2) .
    
    --- width(((new[2]new)[4](new[6]new))[7](new[10](new[15]new))) .

endfm

--- Binary Search Trees

fmod BTREE-SEARCH is
    extending BTREE{Nat} .

    sorts NeBSTree BSTree .
    subsort BSTree < BTree{Nat} .
    subsort NeBSTree < NeBTree{Nat} .

    op isSorted : BTree{Nat} -> Bool . --- check if BTree belongs to BSTree sort.
    ops min max : BTree{Nat} -> Nat .  --- Minimum and maximum value of trees & subtrees.
    --- ops min max : BSTree -> Nat .  --- Min & Max for BSTrees.
    op add : BSTree Nat -> NeBSTree .
    op del : NeBSTree Nat -> BSTree .
    op successor : NeBSTree -> Nat . --- Find natural sucessor of the root of the given tree (e.g. next bigger than root smller than rest of right tree).
    op undef : -> Nat .

    vars U N : Nat .
    vars R1 R2 : NeBTree{Nat} .
    vars T1 T2 : BTree{Nat} .
    vars S1 S2 : [BSTree] .
    vars P1 P2 : [NeBSTree] .

    cmb S1 : BSTree
        if isSorted(S1) .
    
    cmb S1 : NeBSTree
        if isSorted(S1) /\ empty(S1) = false .

    eq min(new [U] new) = U .
    eq min(R1 [U] new) = min(min(R1), U) .
    eq min(new [U] R2) = min(U, min(R2)) .
    eq min(R1 [U] R2) = min(min(min(R1), min(R2)), U) .

    eq max(new [U] new) = U .
    eq max(R1 [U] new) = max(max(R1), U) .
    eq max(new [U] R2) = max(U, max(R2)) .
    eq max(R1 [U] R2) = max(max(max(R1), max(R2)), U) .

    --- ceq min(S1) = min(left(S1)) if empty(left(S1)) = false .
    --- ceq min(S1) = root(S1) if true : Bool .

    --- ceq max(S1) = max(right(S1)) if empty(right(S1)) = false .
    --- ceq max(S1) = root(S1) if true : Bool .
    
    --- Test tree: ((new [5] new) [8] ((new [15] new)[12] new))

    --- Membership

    eq isSorted(new) = true .
    eq isSorted(new [U] new) = true .
    eq isSorted(R1 [U] new) = min(R1) < U .
    eq isSorted(new [U] R2) = max(R2) > U .
    eq isSorted(R1 [U] R2) = min(R1) < U and max(R2) > U and isSorted(R1) and isSorted(R2) .

    --- Example: red in BTREE-SEARCH : isSorted(((new [5] new) [8] ((new [15] new)[17] (new [21] new)))) .

    --- ADD

    ceq add(S1, N) = (new [N] new) if empty(S1) .
    ceq add(S1, N) = ((new [N] new) [root(S1)] right(S1)) if empty(left(S1)) = true /\ N < root(S1) .
    ceq add(S1, N) = (add(left(S1), N) [root(S1)] right(S1)) if empty(left(S1)) = false /\ N < root(S1) .
    ceq add(S1, N) = (left(S1) [root(S1)] (new [N] new)) if empty(right(S1)) = true /\ N > root(S1) .
    ceq add(S1, N) = (left(S1) [root(S1)] add(right(S1), N)) if empty(right(S1)) = false /\ N > root(S1) .

    --- Example: red in BTREE-SEARCH : add(((new [4] (new [7] new)) [8] (new [12] new)), 5) .

    --- DELETE

    ceq del(S1, N) = new if empty(left(S1)) /\ empty(right(S1)) /\ root(S1) == N .
    ceq del(S1, N) = right(S1) if empty(left(S1)) /\ empty(right(S1)) = false /\ root(S1) == N .
    ceq del(S1, N) = left(S1) if empty(left(S1)) = false /\ empty(right(S1)) /\ root(S1) == N .
    ceq del(S1, N) = S1 if empty(left(S1)) /\ empty(right(S1)) /\ root(S1) =/= N .
    ceq del(S1, N) = S1 if N < root(S1) /\ empty(left(S1)) .
    ceq del(S1, N) = (del(left(S1), N) [root(S1)] right(S1)) if N < root(S1) /\ empty(left(S1)) = false .
    ceq del(S1, N) = S1 if N < root(S1) /\ empty(right(S1)) .
    ceq del(S1, N) = (left(S1) [root(S1)] del(right(S1), N)) if N > root(S1) /\ empty(right(S1)) = false .
    ceq del(S1, N) = (left(S1) [successor(S1)] del(right(S1), successor(S1))) if true : Bool .

    --- Example: red in BTREE-SEARCH : del(((new [4] (new [7] new)) [8] (((new [9] new) [10] (new [11] new)) [12] new)), 4) .

    --- SUCCESSOR

    eq successor(S1) = min(right(S1)) .
    
endfm

view Nat from TRIV to NAT is
    sort Elt to Nat .
endv

fmod BTREE-TEST is
    protecting BTREE{Nat} .
endfm

--- fmod BSTREE-TEST is
---     protecting BTREE-SEARCH{Nat} .
--- endfm