mod KHUN-PHAN is
    protecting NAT .
    sorts Piece Board .
    subsort Piece < Board .
    *** each piece carries the coordinates of its upper left corner
    ops empty bigsq smallsq hrect vrect : Nat Nat -> Piece .
    *** board is nonempty multiset of pieces
    op __ : Board Board -> Board [assoc comm] .
    op initial : -> Board .
    eq initial = vrect(1, 1) bigsq(2, 1) vrect(4, 1) empty(1, 3) hrect(2, 3) empty(4, 3) vrect(1, 4) smallsq(2, 4) smallsq(3, 4) vrect(4, 4) smallsq(2, 5) smallsq(3, 5) .

    vars X Y : Nat .

    rl [sqr] : smallsq(X, Y) empty(s(X), Y) => empty(X, Y) smallsq(s(X), Y) .
    rl [sql] : smallsq(s(X), Y) empty(X, Y) => empty(s(X), Y) smallsq(X, Y) .
    rl [squ] : smallsq(X, s(Y)) empty(X, Y) => empty(X, s(Y)) smallsq(X, Y) .
    rl [sqd] : smallsq(X, Y) empty(X, s(Y)) => empty(X, Y) smallsq(X, s(Y)) .
    rl [Sqr] : bigsq(X, Y) empty(s(s(X)), Y) empty(s(s(X)), s(Y)) => empty(X, Y) empty(X, s(Y)) bigsq(s(X), Y) .
    rl [Sql] : bigsq(s(X), Y) empty(X, Y) empty(X, s(Y)) => empty(s(s(X)), Y) empty(s(s(X)), s(Y)) bigsq(X, Y) .
    rl [Squ] : bigsq(X, s(Y)) empty(X, Y) empty(s(X), Y) => empty(X, s(s(Y))) empty(s(X), s(s(Y))) bigsq(X, Y) .
    rl [Sqd] : bigsq(X, Y) empty(X, s(s(Y))) empty(s((X), s(s(Y))) => empty(X, Y) empty(s(X), Y) bigsq(X, s(Y)) .

    rl [hrectr] : hrect(X, Y) empty(s(s(X)), Y) => empty(X, Y) hrect(s(X), Y) .
    rl [hrectl] : hrect(s(X), Y) empty(X, Y) => empty(s(s(X)), Y) hrect(X, Y) .
    rl [hrectu] : hrect(X, s(Y)) empty(X, Y) empty(s(X), Y) => empty(X, s(Y)) empty(s(X), s(Y)) hrect(X, Y) .
    rl [hrectd] : hrect(X, Y) empty(X, s(Y)) empty(s(X), s(Y)) => empty(X, Y) empty(s(X), Y) hrect(X, s(Y)) .
    rl [vrectr] : vrect(X, Y) empty(s(X), Y) empty(s(X), s(Y)) => empty(X, Y) empty(X, s(Y)) vrect(s(X), Y) .
    rl [vrectl] : vrect(s(X), Y) empty(X, Y) empty(X, s(Y)) => empty(s(X), Y) empty(s(X), s(Y)) vrect(X, Y) .
    rl [vrectu] : vrect(X, s(Y)) empty(X, Y) => empty(X, s(s(Y))) vrect(X, Y) .
    rl [vrectd] : vrect(X, Y) empty(X, s(s(Y))) => empty(X, Y) vrect(X, s(Y)) .
endm