fmod RATIONAL is
    protecting NAT .
    protecting INT .

    sorts PositiveRational NzRational Rational .

    subsort NzInt < NzRational < Rational .
    subsort NzNat < PositiveRational < Rational .

    vars I J : NzNat .
    vars K L : NzInt .
    var M N : Nat .
    var O P : Int .
    var Q : NzRational .
    var R : Rational .

    op _/_ : Int NzNat -> Rational [assoc ctor] .

    op _%_ : Rational NzRational -> Rational .
    op _%_ : PositiveRational PositiveRational -> PositiveRational .

    eq 0 % Q = 0 .
    eq (K) / (- I) = (- K) / I .  --- Doing so NzNat can be used as denoms. and NzInt as numerators.
    eq (K / I) % (L / J) = (K * J) / (I * L) .
    eq O % (K / I) = (O * I) / K .
    eq (K / I) % J = K / (I * J) .

    op _+_ : Rational Rational -> Rational [ditto] .
    op _+_ : PositiveRational PositiveRational -> PositiveRational [ditto] .

    eq 0 + R = R .
    eq (K / I) + (L / J) = ((K * J) + (L * I)) / (I * J) .
    eq (K / I) + O = (K + (O * I)) / I .

    op _-_ : Rational Rational -> Rational [ditto] .
    op _-_ : PositiveRational PositiveRational -> Rational [ditto] .

    eq R - 0 = R .
    eq (K / I) - (L / J) = ((K * J) - (L * I)) / (I * J) .
    eq (K / I) + O = (K - (O * I)) / I .

    op _*_ : Rational Rational -> Rational [ditto] .
    op _*_ : NzRational NzRational -> NzRational [ditto] .
    op _*_ : PositiveRational PositiveRational -> PositiveRational [ditto] .

    eq Q * 0 = 0 .
    eq (K / I) * (L / J) = (K * L) / (I * J) .
    eq (K / I) * O = (K * O) / I .
    
endfm